package ds

import "errors"

var (
	ErrMissingAutoGeneratedKey = errors.New("Cannot resolve auto generated key. Model needs a key to be used with ds.Datastore.")
	ErrMissingStringId         = errors.New(`Model is missing StringId. String field tagged with db:"id" cannot be empty`)
)
