package appx_test

import "github.com/drborges/appx"

type Post struct {
	appx.Model
	Description string
}

// Post uses incomplete keys in datastore a.k.a IntID == 0, StringID == ""
// That means an int ID will be auto generated by datastore upon creation
// By omitting IntID and StringID from the KeyMetadata forces the model
// to use incomplete keys.
func (this Post) KeyMetadata() *appx.KeyMetadata {
	return &appx.KeyMetadata{
		Kind: "Posts",
	}
}
