package ds_test

import (
	"appengine/aetest"
	"github.com/drborges/ds"
	. "github.com/smartystreets/goconvey/convey"
	"testing"
	"appengine/datastore"
)

func TestKeyMetadata(t *testing.T) {
	c, _ := aetest.NewContext(nil)
	defer c.Close()

	Convey("Key metadata", t, func() {
		Convey("NewKey", func() {
			Convey("returns key with parent key properly set", func() {
				parentKey := datastore.NewKey(c, "Account", "", 0, nil)
				post := &Post{Description: "Super cool!"}
				post.SetParentKey(parentKey)

				key := ds.NewKey(c, post)

				So(key.Parent(), ShouldResemble, parentKey)
			})
		})

		Convey("ResolveKey", func() {
			Convey("succesfully sets model key", func() {
				parentKey := datastore.NewKey(c, "Account", "", 0, nil)
				tag := &Tag{Name: "golang"}
				tag.SetParentKey(parentKey)

				err := ds.ResolveKey(c, tag)

				So(err, ShouldBeNil)
				So(tag.Key(), ShouldNotBeNil)
				So(tag.Key().StringID(), ShouldEqual, tag.Name)
				So(tag.Key().Parent(), ShouldResemble, parentKey)
			})

			Convey("returns ErrMissingAutoGeneratedKey if key is not set", func() {
				post := &Post{Description: "Super cool!"}

				err := ds.ResolveKey(c, post)

				So(post.Key(), ShouldBeNil)
				So(err, ShouldEqual, ds.ErrUnresolvableKey)
			})

			Convey("returns ErrMissingAutoGeneratedKey if key set is incomplete", func() {
				post := &Post{Description: "Super cool!"}
				post.SetKey(datastore.NewIncompleteKey(c, "Posts", nil))

				err := ds.ResolveKey(c, post)

				So(err, ShouldEqual, ds.ErrUnresolvableKey)
			})
		})
	})
}
